spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/real_estate?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qaz0802

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

openApi:
  callBackUrl: "http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev"
  serviceKey: "%2F0SnlHeNzahA4qk3TvRa2ghBhFuIJ8SoPRQnqaWNdxVBkRmtEzUS5hZnY8W9EInCL9Q9LTXOmOHf7zrno%2FeVjA%3D%3D"
